// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI20.Data;

namespace WebAPI20.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.4.20220.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI20.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebAPI20.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "James Cameron",
                            Genre = "Drama, Romance",
                            Title = "Titanic",
                            YearCreated = 1997
                        },
                        new
                        {
                            Id = 2,
                            Director = "Christopher Nolan",
                            Genre = "Action, Adventure, Sci-fi",
                            Title = "Inception",
                            YearCreated = 2010
                        },
                        new
                        {
                            Id = 3,
                            Director = "Ridley Scott",
                            Genre = "Action, Adventure, Drama",
                            Title = "Gladiator",
                            YearCreated = 2000
                        },
                        new
                        {
                            Id = 4,
                            Director = "Brian De Palma",
                            Genre = "Crime, Drama",
                            Title = "Scarface",
                            YearCreated = 1983
                        },
                        new
                        {
                            Id = 5,
                            Director = "James Cameron",
                            Genre = "Action, Adventure, Sci-fi",
                            Title = "The Avatar",
                            YearCreated = 2009
                        },
                        new
                        {
                            Id = 6,
                            Director = "Ridley Scott",
                            Genre = "Horror, Sci-fi",
                            Title = "Alien",
                            YearCreated = 1979
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
